# Server port
server.port=8187

# DataSource Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/microservices?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Sriram@123
spring.application.name=Movie-Info-Service
# JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka Client Configuration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Eureka Server Configuration
eureka.server.enable-self-preservation=false

# Default Zone for Eureka Server
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
